# Site-wide config for Jupyter Book
title: "Project 1 â€“ Central Park Squirrel Analysis"
author: "Robin Zhao"

only_build_toc_files: true
exclude_patterns:
  - .venv/*
  - _build/*
  - .github/*
  - .pytest_cache/*

execute:
  execute_notebooks: "off"

sphinx:
  config:
    myst_heading_anchors: 4
    html_js_files:
      - https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.7/require.min.js
    suppress_warnings:
      - mystnb.unknown_mime_type

